version: '2'

services:
  grafana:
    image: bitnami/grafana
    ports:
      - 3000:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
    volumes:
      - ./grafanadata:/var/lib/grafana

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./output.json:/usr/share/nginx/html/play.json
  # volumes:
