service: blackfriday

frameworkVersion: '2'

useDotenv: true
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: production
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt:
                - scoreTable
                - Arn
        - Effect: 'Allow'
          Action:
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt:
                - scoreTable
                - Arn
          Condition:
            ForAllValues:StringEquals:
              dynamodb:Attributes:
                - handle
                - score
                - id

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST

  environment:
    SCORE_TABLE: ${self:custom.tableNames.scoreTable}

functions:
  statichttp:
    handler: staticHandler.pageHandler
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /{any+}
          method: GET

  play:
    handler: index.play
    timeout: 12
    events:
      - httpApi:
          path: /
          method: POST
  
  scoreboard:
    handler: scoreboard.scoreboard
    timeout: 12
    events:
      - httpApi:
          path: /scoreboard
          method: GET

package:
  include:
    - 'docs/**'
  exclude:
    - 'tests/**'
    - '*.md'
    - 'wallaby.js'
    - 'jest.config.js'
    - 'package-lock.json'
    # - "node_modules/aws-sdk/**"
    - 'coverage/**'
    - '.*'
    - '.*/**'

resources:
  Resources:
    scoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNames.scoreTable}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: score
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: score
            AttributeType: 'N'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2

custom:
  bundle:
    linting: false
    # caching: false

    sourcemaps: false
    copyFiles:
      - from: 'docs/*'
        to: './'

  dynamodb:
    noStart: true

  tableNames:
    scoreTable: blackFridayScoreTable

    stages:
      - production
    start:
      migrate: true
